server:
  port: ${PORT:8003}
  
spring:
  application:
    name: "user-api"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      path: /h2-console
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}