server:
  port: ${PORT:8000}
  
spring:
  application:
    name: "user-api"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      path: /h2-console
      enabled: true
